from typing import Any, TypeVar

class Symbol:
    def __init__(self, name: str) -> None: ...

ExprT = TypeVar("ExprT", bound="Expr")

class Expr:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __add__(self, other: Any) -> Expr: ...
    def __radd__(self, other: Any) -> Expr: ...
    def __sub__(self, other: Any) -> Expr: ...
    def __rsub__(self, other: Any) -> Expr: ...
    def __mul__(self, other: Any) -> Expr: ...
    def __rmul__(self, other: Any) -> Expr: ...
    def __truediv__(self, other: Any) -> Expr: ...
    def __rtruediv__(self, other: Any) -> Expr: ...
    def __pos__(self) -> Expr: ...
    def __neg__(self) -> Expr: ...
    def __abs__(self) -> Expr: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def simplify(self) -> Expr: ...
    def evalf(self) -> Expr: ...
    def subs(self, subs: dict[Symbol | str, int | float | complex | Expr]) -> Expr: ...
    def xreplace(self, subs: dict[Expr, int | float | complex | Expr]) -> Expr: ...
    @property
    def free_symbols(self) -> set[Symbol]: ...
    def atoms(self, typ: type[ExprT]) -> set[ExprT]: ...

class Integer(Expr):
    def __init__(self, value: int) -> None: ...

class Float(Expr):
    def __init__(self, value: float) -> None: ...
    @property
    def num(self) -> int: ...

I: Expr

def sympify(value: Any) -> Expr: ...
def simplify(expr: Expr) -> Expr: ...
def diff(expr: Expr, var: Symbol) -> Expr: ...
