from typing import Any, Sized, Sequence, ClassVar, TypeVar, Generic
from typing_extensions import Self
from numpy.typing import NDArray
from numpy import bool_, uint8, float64, complex128

class Map:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> None: ...
    def __len__(self) -> int: ...

class RootOfUnity:
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def to_phase(self) -> int | bool: ...

class Sign(RootOfUnity):
    def __init__(self, phase: bool) -> None: ...
    def to_phase(self) -> bool: ...

class ComplexSign(RootOfUnity):
    def __init__(self, phase: int) -> None: ...
    def to_phase(self) -> int: ...

class BaseVec(Sized):
    def __init__(self, size: int) -> None: ...
    def __len__(self) -> int: ...
    @classmethod
    def parse(self, string: str) -> Self: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...
    def append(self, value: Any) -> None: ...
    def resize(self, new_size: int) -> None: ...
    def same_as(self, other: Self) -> bool: ...
    def extend_internal(self) -> None: ...
    def extend_external(self, other: Self) -> None: ...

class SignVec(BaseVec):
    @classmethod
    def from_phases(cls, phases: NDArray[bool_]) -> Self: ...
    def __getitem__(self, index: int) -> Sign: ...
    def __setitem__(self, index: int, value: Sign) -> None: ...

class ComplexSignVec(BaseVec):
    @classmethod
    def from_phases(cls, phases: NDArray[uint8]) -> Self: ...
    def __getitem__(self, index: int) -> ComplexSign: ...
    def __setitem__(self, index: int, value: ComplexSign) -> None: ...

class RealVec(BaseVec):
    @classmethod
    def from_array(cls, array: NDArray[float64]) -> Self: ...
    def to_array(self) -> NDArray[float64]: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def same_as(self, other: RealVec) -> bool: ...

class ComplexVec(BaseVec):
    @classmethod
    def from_array(cls, array: NDArray[complex128]) -> Self: ...
    def to_array(self) -> NDArray[complex128]: ...
    def __getitem__(self, index: int) -> complex: ...
    def __setitem__(self, index: int, value: complex) -> None: ...
    def same_as(self, other: ComplexVec) -> bool: ...

class Qubits(Sized):
    def __init__(self, qubits: Qubits) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    @classmethod
    def from_count(cls, source: int) -> Self: ...
    @classmethod
    def from_offset(cls, i: int, n: int) -> Self: ...
    @classmethod
    def from_inds(cls, inds: list[int]) -> Self: ...
    @classmethod
    def from_hilbert_space_dim(cls, n: int) -> Self: ...

class ImplArray(Sized):
    def resize(self, n: int) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def cmpnts_clone(self, inds: Sequence[int] | None) -> Self: ...
    def cmpnts_eq(
        self, inds: Sequence[int] | None, other: Self, other_inds: Sequence[int] | None
    ) -> bool: ...
    def cmpnt_copy_internal(self, i_dst: int, i_src: int) -> None: ...
    def cmpnt_copy_external(self, i_dst: int, src: Self, i_src: int) -> None: ...
    def same_as(self, other: Self) -> bool: ...
    def mapped_insert(self, map: Map, other: Self, index: int) -> int: ...
    def mapped_lookup(self, map: Map, other: Self, index: int) -> int | None: ...
    def mapped_remove(self, map: Map, other: Self, index: int) -> int | None: ...
    def mapped_equal(self, map: Map, other: Self) -> bool: ...

ElemT = TypeVar("ElemT")
SpringsT = TypeVar("SpringsT", bound=Springs)

class QubitArray(Generic[SpringsT, ElemT], ImplArray):
    qubits: Qubits

    def __init__(self, qubits: Qubits | None = ..., source: SpringsT | None = ...) -> None: ...
    def relabel(self, qubits: Any) -> None: ...
    def standardize(self, n: int) -> None: ...
    def standardized(self, n: int) -> Self: ...
    def append_clear(self) -> None: ...
    def cmpnt_clear(self, i: int) -> None: ...
    def cmpnt_equal(self, i_lhs: int, rhs: Self, i_rhs: int) -> bool: ...
    def cmpnt_set_from_list(self, index: int, source: list[ElemT]) -> None: ...
    def cmpnt_set_from_spring(self, index: int, source: SpringsT, spring_index: int) -> Any: ...
    def cmpnt_get_list(self, index: int) -> list[ElemT]: ...
    def cmpnt_count(self, index: int, value: ElemT) -> int: ...
    def cmpnt_to_string(self, index: int) -> str: ...
    def refresh_map(self, map: Map) -> None: ...

class QubitPauliArray(QubitArray[PauliSprings, PauliMatrix]):
    def __init__(
        self, qubits: Qubits | None = ..., source: PauliSprings | None = ...
    ) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, source: dict[str, Any]) -> Self: ...
    def cmpnt_set_from_dict(
        self, index: int, source: dict[int, PauliMatrix]
    ) -> None: ...
    def cmpnt_set_from_list(self, index: int, source: list[PauliMatrix]) -> None: ...
    def cmpnt_set_from_spring(
        self, index: int, source: PauliSprings, spring_index: int
    ) -> ComplexSign: ...
    def cmpnt_get_pauli(self, index: int, qubit: int) -> PauliMatrix: ...
    def cmpnt_set_pauli(self, index: int, qubit: int, pauli: PauliMatrix) -> None: ...
    def cmpnt_get_list(self, index: int) -> list[PauliMatrix]: ...
    def cmpnt_get_dict(self, index: int) -> dict[int, PauliMatrix]: ...
    def cmpnt_count(self, index: int, pauli: PauliMatrix) -> int: ...
    def cmpnt_mul(
        self, index: int, rhs: QubitPauliArray, rhs_index: int
    ) -> tuple[QubitPauliArray, ComplexSign]: ...
    def cmpnt_to_sparse_matrix(self, index: int, big_endian: bool = ...) -> Any: ...
    def cmpnt_phase_of_mul(
        self, index: int, rhs: QubitPauliArray, rhs_index: int
    ) -> ComplexSign: ...
    def cmpnt_matrices_imul_internal(self, index: int, rhs_index: int) -> None: ...
    def cmpnt_matrices_imul_external(
        self, index: int, rhs: QubitPauliArray, rhs_index: int
    ) -> None: ...
    def cmpnt_imul_internal(self, index: int, rhs_index: int) -> ComplexSign: ...
    def cmpnt_imul_external(
        self, index: int, rhs: QubitPauliArray, rhs_index: int
    ) -> ComplexSign: ...
    def cmpnt_commutes_with(
        self, index: int, rhs: QubitPauliArray, rhs_index: int
    ) -> bool: ...
    def compatibility_matrix(self) -> NDArray[uint8]: ...
    def centralizer_and_remainder(self) -> tuple[QubitPauliArray, QubitPauliArray]: ...
    @classmethod
    def with_phases(
        cls, qubits: Qubits | None = ..., source: PauliSprings | None = ...
    ) -> tuple[QubitPauliArray, ComplexSignVec]: ...
    def conj_clifford_list(self, gates: CliffordGateList) -> SignVec: ...
    def lexicographic_sort(self, ascending: bool = ...) -> None: ...
    def lexicographic_sort_with_sign_vec(
        self, coeffs: SignVec, ascending: bool = ...
    ) -> None: ...
    def lexicographic_sort_with_complex_sign_vec(
        self, coeffs: ComplexSignVec, ascending: bool = ...
    ) -> None: ...
    def lexicographic_sort_with_real_vec(
        self, coeffs: RealVec, ascending: bool = ...
    ) -> None: ...
    def lexicographic_sort_with_complex_vec(
        self, coeffs: ComplexVec, ascending: bool = ...
    ) -> None: ...
    @staticmethod
    def lincomb_mul_real(
        lhs_impl: QubitPauliArray,
        lhs_coeffs: RealVec,
        rhs_impl: QubitPauliArray,
        rhs_coeffs: RealVec,
        out_impl: QubitPauliArray,
        out_map: Map,
        out_coeffs: ComplexVec,
    ) -> None: ...
    @staticmethod
    def lincomb_mul_complex(
        lhs_impl: QubitPauliArray,
        lhs_coeffs: ComplexVec,
        rhs_impl: QubitPauliArray,
        rhs_coeffs: ComplexVec,
        out_impl: QubitPauliArray,
        out_map: Map,
        out_coeffs: ComplexVec,
    ) -> None: ...
    @staticmethod
    def lincomb_to_sparse_real(
        cmpnts: QubitPauliArray, coeffs: RealVec, big_endian: bool = ...
    ) -> Any: ...
    @staticmethod
    def lincomb_to_sparse_complex(
        cmpnts: QubitPauliArray, coeffs: ComplexVec, big_endian: bool = ...
    ) -> Any: ...
    @staticmethod
    def lincomb_project_into_ortho_subspace_real(
        cmpnts: QubitPauliArray,
        coeffs: RealVec,
        subspace: QubitStateArray,
    ) -> NDArray[float64]: ...
    @staticmethod
    def lincomb_project_into_ortho_subspace_complex(
        cmpnts: QubitPauliArray,
        coeffs: ComplexVec,
        subspace: QubitStateArray,
    ) -> NDArray[complex128]: ...
    @staticmethod
    def lincomb_project_into_nonortho_subspace_real(
        cmpnts: QubitPauliArray,
        coeffs: RealVec,
        subspace_cmpnts: Sequence[QubitStateArray],
        subspace_maps: Sequence[Map],
        subspace_coeffs: Sequence[RealVec],
    ) -> tuple[NDArray[float64], NDArray[float64]]: ...
    @staticmethod
    def lincomb_project_into_nonortho_subspace_complex(
        cmpnts: QubitPauliArray,
        coeffs: ComplexVec,
        subspace_cmpnts: Sequence[QubitStateArray],
        subspace_maps: Sequence[Map],
        subspace_coeffs: Sequence[ComplexVec],
    ) -> tuple[NDArray[complex128], NDArray[complex128]]: ...
    def apply_to_state_real(
        self,
        coeffs: RealVec,
        state_impl: QubitStateArray,
        state_coeffs: RealVec,
        out_impl: QubitStateArray,
        out_map: Map,
        out_coeffs: ComplexVec,
    ) -> None: ...
    def apply_to_state_complex(
        self,
        coeffs: ComplexVec,
        state_impl: QubitStateArray,
        state_coeffs: ComplexVec,
        out_impl: QubitStateArray,
        out_map: Map,
        out_coeffs: ComplexVec,
    ) -> None: ...
    def mat_elem_real(
        self,
        coeffs: RealVec,
        bra_impl: QubitStateArray,
        bra_coeffs: RealVec,
        ket_impl: QubitStateArray,
        ket_coeffs: RealVec,
    ) -> float: ...
    def mat_elem_complex(
        self,
        coeffs: ComplexVec,
        bra_impl: QubitStateArray,
        bra_coeffs: ComplexVec,
        ket_impl: QubitStateArray,
        ket_coeffs: ComplexVec,
    ) -> complex: ...
    def save_to_file(self, path: str) -> None: ...
    @classmethod
    def load_from_file(cls, path: str) -> Self: ...

class QubitStateArray(QubitArray[BinarySprings, bool]):
    qubits: Qubits

    def __init__(
        self, qubits: Qubits | None = ..., source: BinarySprings | None = ...
    ) -> None: ...
    def cmpnt_set_bit(self, i_cmpnt: int, i_qubit: int, bit: bool) -> None: ...
    def cmpnt_get_bit(self, i_cmpnt: int, i_qubit: int) -> bool: ...
    def cmpnt_set_from_list(self, index: int, source: list[bool]) -> None: ...
    def cmpnt_set_from_set(self, index: int, source: set[int]) -> None: ...
    def cmpnt_set_from_spring(
        self, index: int, source: BinarySprings, spring_index: int
    ) -> None: ...
    def cmpnt_get_list(self, index: int) -> list[bool]: ...
    def cmpnt_get_set(self, index: int) -> set[int]: ...
    def cmpnt_pauli_string_imul(
        self, index: int, paulis: QubitPauliArray, i_pauli: int
    ) -> ComplexSign: ...
    def cmpnt_count(self, index: int, bit: bool) -> int: ...
    def to_dense_real(self, coeffs: RealVec, big_endian: bool) -> NDArray[float64]: ...
    def to_dense_complex(self, coeffs: ComplexVec, big_endian: bool) -> NDArray[complex128]: ...
    def from_dense_real(
        self, map: Map, coeffs: RealVec, source: list[float], big_endian: bool
    ) -> None: ...
    def from_dense_complex(
        self, map: Map, coeffs: ComplexVec, source: list[complex], big_endian: bool
    ) -> None: ...
    def vdot_real(
        self,
        map: Map,
        coeffs: RealVec,
        rhs_cmpnts: QubitStateArray,
        rhs_coeffs: RealVec,
    ) -> float: ...
    def vdot_complex(
        self,
        map: Map,
        coeffs: ComplexVec,
        rhs_cmpnts: QubitStateArray,
        rhs_coeffs: ComplexVec,
    ) -> complex: ...

class PauliMatrix:
    I: ClassVar[PauliMatrix]
    X: ClassVar[PauliMatrix]
    Y: ClassVar[PauliMatrix]
    Z: ClassVar[PauliMatrix]

class Springs(Sized):
    def __init__(self, source: str) -> None: ...
    def __len__(self) -> int: ...
    def default_n_qubit(self) -> int: ...

class PauliSprings(Springs):
    pass

class BinarySprings(Springs):
    pass

class JordanWignerMapper:
    def __init__(
        self, qubits: Qubits, mode_ordering: list[int] | None = ...
    ) -> None: ...
    def op_load_product(self, ladder_operators: list[tuple[int, bool]]) -> None: ...
    def op_contribute_real(
        self,
        cmpnts: QubitPauliArray,
        map: Map,
        coeffs: RealVec,
        scalar: float,
    ) -> None: ...
    def op_contribute_complex(
        self,
        cmpnts: QubitPauliArray,
        map: Map,
        coeffs: ComplexVec,
        scalar: complex,
    ) -> None: ...
    def op_encode_real(
        self,
        fermion_ops: Sequence[tuple[Sequence[tuple[int, bool]], float]],
        cmpnts: QubitPauliArray,
        map: Map,
        coeffs: RealVec,
    ) -> None: ...

class CliffordGateList:
    def __init__(self) -> None: ...
    def push_h(self, i_qubit: int) -> None: ...
    def push_s(self, i_qubit: int) -> None: ...
    def push_cx(self, i_control: int, i_target: int) -> None: ...
    def __str__(self) -> str: ...
