name: Publish docs to GitHub Pages

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      UV_FROZEN: 1

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: extractions/setup-just@v3
        with:
          just-version: '1.40.0'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: "0.11.3"

      - name: Build docs
        run: |
          cd zixy-py/docs
          just build-strict
